server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: XbFzfrbK73n2jA3fGxqY5B9X7Tf2E9U7np2yL3cOqG2s3Tz6hU5qZ7e8oQ2vR3tYxP9wZ7fX8vL9mQ1sW3hP6nR4jV2yU3tF8
  expiration: 3600000 # 1 hora em milissegundos

logging:
  level:
    org.springframework: INFO
    com.example.orders: DEBUG
